CREATE TABLE Produkt (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	bezeichnung TEXT NOT NULL,
	beschreibung TEXT NOT NULL,
	details TEXT DEFAULT NULL,
	preis REAL NOT NULL DEFAULT 0.0
);

CREATE TABLE Produktbild (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	bildpfad TEXT NOT NULL,
	produktId INTEGER NOT NULL,
	on_homepage BOOLEAN NOT NULL DEFAULT FALSE,
	CONSTRAINT fk_Produktbild1 FOREIGN KEY (produktId) REFERENCES Produkt(id)
);


CREATE TABLE Adresse (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	strasse TEXT NOT NULL,
	hausnummer TEXT NOT NULL,
	plz TEXT NOT NULL,
	ort TEXT NOT NULL
);

CREATE TABLE Person (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	anrede INTEGER NOT NULL DEFAULT 0,
	vorname TEXT NOT NULL,
	nachname TEXT NOT NULL,
	adresseId INTEGER NOT NULL,
	telefonnummer TEXT NOT NULL,
	email TEXT NOT NULL,
	geburtstag TEXT DEFAULT NULL,
	CONSTRAINT fk_Person1 FOREIGN KEY (adresseId) REFERENCES Adresse(id)
);

CREATE TABLE Benutzer (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	benutzername TEXT NOT NULL UNIQUE,
	passwort TEXT NOT NULL,
	benutzerrolleId INTEGER NOT NULL,
	personId INTEGER DEFAULT NULL,
	CONSTRAINT fk_Benutzer1 FOREIGN KEY (benutzerrolleId) REFERENCES Benutzerrolle(id),
	CONSTRAINT fk_Benutzer2 FOREIGN KEY (personId) REFERENCES Person(id)
);

CREATE TABLE Benutzerrolle (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	bezeichnung TEXT NOT NULL
);

CREATE TABLE Zahlungsart (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	bezeichnung TEXT NOT NULL
);

CREATE TABLE Bestellung (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	bestellzeitpunkt TEXT NOT NULL,
	bestellerId INTEGER DEFAULT NULL,
	zahlungsartId INTEGER NOT NULL,
	CONSTRAINT fk_Bestellung1 FOREIGN KEY (bestellerId) REFERENCES Person(id),
	CONSTRAINT fk_Bestellung2 FOREIGN KEY (zahlungsartId) REFERENCES Zahlungsart(id)
);

CREATE TABLE Bestellposition (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	bestellungId INTEGER NOT NULL,
	produktId INTEGER NOT NULL,
	menge INTEGER NOT NULL DEFAULT 1,
	CONSTRAINT fk_Bestellposition1 FOREIGN KEY (bestellungId) REFERENCES Bestellung(id),
	CONSTRAINT fk_Bestellposition2 FOREIGN KEY (produktId) REFERENCES Produkt(id)
);

